version: "3"
services:
  main:
    build:
      context: .
      dockerfile: dev.Dockerfile
    env_file: .env
    volumes:
      - ".:/usr/src/app"
  ngrok:
    image: wernight/ngrok
    env_file: .ngrok.env
    environment:
      NGROK_PORT: main:3000
    ports:
      - 3001:4040
  db:
    image: mongo
    volumes:
      - "db_volume:/data/db"
  mongo-express:
    image: mongo-express
    ports:
      - 3002:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: db
volumes:
  db_volume:
